YOSYS = yosys
GP4PAR = gp4par
GP4PROG = gp4prog
VERILATOR = verilator

all : $(PROJECT).txt

$(PROJECT).json : $(SOURCE)
	$(YOSYS) -p 'read_verilog $(SOURCE)' \
	-p 'synth_greenpak4 -part $(PART) -json $(PROJECT).json'

%.txt : %.json
	$(GP4PAR) $< -o $@ -p $(PART)

emulate : $(PROJECT).txt
	$(GP4PROG) -v 3.3 --emulate $(PROJECT).txt $(NETS)

lint :
	$(VERILATOR) --lint-only $(SOURCE)

clean :
	rm -f *.txt *.json

.PHONY : clean emulate lint all
