% Self-similar tree generated by random process

clc
clear
close all
format

% Set default interpreter for xlabel, ylabel, title, ...
set(0, 'defaultTextInterpreter', 'latex');
set(groot, 'defaultAxesTickLabelInterpreter', 'latex');
set(groot, 'defaultLegendInterpreter', 'latex');

% Starting point
P = [0.5; 0];
% Number of iterations
N = 10e4;

points = zeros(N, 2);
points(1,:) = P.';

for i=2:N
    r = rand;
    if r <= 0.1
        P = P .* [0.05; 0.6];
    elseif r <= 0.2
        P = P .* [0.05; -0.5] + [0; 1];
    elseif r <= 0.4
        P = [0.46 -0.15; 0.39 0.38] * P + [0; 0.6];
    elseif r <= 0.6
        P = [0.47 -0.15; 0.17 0.42] * P + [0; 1.1];
    elseif r <= 0.8
        P = [0.43 0.28; -0.25 0.45] * P + [0; 1.0];
    else
        P = [0.42 0.26; -0.35 0.31] * P + [0; 0.7];
    end
    
    points(i,:) = P.';
end

figure
scatter(points(:,1), points(:,2), 1)